<?xml version="1.0" encoding="UTF-8"?><testrun name="UserDAOTestCase" project="ShoppingCartBackEnd" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.niit.shoppingcart.UserDAOTestCase" time="0.406">
    <testcase name="createUserTestCase" classname="com.niit.shoppingcart.UserDAOTestCase" time="0.406">
      <error>org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement&#13;
	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:167)&#13;
	at org.springframework.orm.hibernate4.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:730)&#13;
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:592)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)&#13;
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:487)&#13;
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)&#13;
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)&#13;
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)&#13;
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)&#13;
	at com.sun.proxy.$Proxy30.save(Unknown Source)&#13;
	at com.niit.shoppingcart.UserDAOTestCase.createUserTestCase(UserDAOTestCase.java:52)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
Caused by: org.hibernate.exception.DataException: could not execute statement&#13;
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:135)&#13;
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)&#13;
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)&#13;
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)&#13;
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62)&#13;
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3124)&#13;
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3581)&#13;
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:104)&#13;
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)&#13;
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)&#13;
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)&#13;
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)&#13;
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)&#13;
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)&#13;
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)&#13;
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)&#13;
	at org.springframework.orm.hibernate4.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:584)&#13;
	... 33 more&#13;
Caused by: org.h2.jdbc.JdbcSQLException: Data conversion error converting "'sairam' (USER: CONTACT NUMBER NOT NULL)"; SQL statement:
insert into user (contact, name, password, role, id) values (?, ?, ?, ?, ?) -- (?1, ?2, ?3, ?4, ?5) [22018-194]&#13;
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)&#13;
	at org.h2.message.DbException.get(DbException.java:179)&#13;
	at org.h2.message.DbException.get(DbException.java:155)&#13;
	at org.h2.table.Column.convert(Column.java:154)&#13;
	at org.h2.command.dml.Insert.insertRows(Insert.java:143)&#13;
	at org.h2.command.dml.Insert.update(Insert.java:114)&#13;
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)&#13;
	at org.h2.command.Command.executeUpdate(Command.java:258)&#13;
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:354)&#13;
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:158)&#13;
	at java.lang.Thread.run(Unknown Source)&#13;
&#13;
	at org.h2.engine.SessionRemote.done(SessionRemote.java:629)&#13;
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:203)&#13;
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)&#13;
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)&#13;
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)&#13;
	... 46 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
